spring:
  config:
    activate:
      on-profile: dev
  swagger:
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
        ddl-auto: update
openapi:
  service:
    api-docs: tasko-api
    server: http://${SERVER_HOST}:${SERVER_PORT_DEV}
    title: Tasko API
    version: 1.0.0


