spring:
  config:
    activate:
      on-profile: test
  swagger:
    enabled: false

openapi:
  service:
    api-docs: tasko-api
    server: http://${SERVER_HOST}:${SERVER_PORT_TEST}
    title: Tasko API
    version: 1.0.0


